using System.Collections;
public enum ResType
{
    Money = 0,
    Knowleges = 1,
    Votes = 2,
    Crystalls = 3,
    OpenedFields = 4,
    OpenedSlots = 5,
    BuildSpeed = 6,
    ClickForce = 7,
    BuildSpeedForVotes = 8,
    BuildSpeedForCristalls = 9,
    BuildSpeedForKnowleges = 10,
    ClickForceForVotes = 11,
    ClickForceForCristalls = 12,
    ClickForceForKnowleges = 13,
    MoneyIncome = 14,
    KnowlegesIncome = 15,
    VotesInkome = 16,
    CristallsIncome = 17,
    WaterIncome = 18,
    GroundIncome = 19,
    MountainsIncome = 20,
    GreenIncome = 21,
    BlueIncome = 22,
    RedIncome = 23,
    AIncome = 24,
    BIncome = 25,
    CIncome = 26,
    DIncome = 27,
    EIncome = 28,
    FIncome = 29,
    GIncome = 30,
    HIncome = 31,
    IIncome = 32,
    BuildPoints = 33,
    RedMana = 34,
    PurpleMana = 35,
    YellowMana = 36,
    MoneyChangeInc = 37,
    KnowlegesChangeInc = 38,
    VotesChangeInc = 39,
    CrystallsChangeInc = 40,
    MaxMana = 41
}

